version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hanamichi
      POSTGRES_DB: vistas-db
    networks:
      - app-net

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hanamichi
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vistas-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hanamichi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres
    networks:
      - app-net

  frontend:
    build: ../front-vistas/
    container_name: vue-frontend
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - spring-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
