version: '3'
services:
  frontend-vistas:
    container_name: frontend-vistas
    build: ../front-vistas/.
    ports:
      - 5173:80
    networks:
      - app-net

  spring-vistas:
    build: .
    container_name: spring-vistas
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://24.144.93.247:5432/vistas_db
      - SPRING_DATASOURCE_USERNAME=vistas_user
      - SPRING_DATASOURCE_PASSWORD=vistas123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
