version: '3'
services:
  postgres-vistas:
    container_name: postgres-vistas
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hanamichi
      POSTGRES_DB: vistas-db
    networks:
      - app-net

  frontend-vistas:
    container_name: frontend-vistas
    build: ../front-vistas/.
    ports:
      - 5173:80
    networks:
      - app-net

  spring-vistas:
    build: .
    container_name: spring-vistas
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hanamichi
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-vistas:5432/vistas-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hanamichi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
